apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
        - pause: { duration: 120s }
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/ultracln/ci_cd_lab@sha256:c77ff9308e466a995e321126f1aa7a6f4f1245e2573b676a719b5f00fd52bbe0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
